# 1.Importing Libraries

In [1]:
#Loading the datasets

import pandas as pd
import numpy as np
import matplotlib as plt


# 2.Importing datasets

In [2]:
#Importing dataset

dataset=pd.read_csv('dataset.csv')

In [3]:
dataset

D    Age  Income  Gender Marital Status Buys
0    1    <21    High    Male         Single   No
1    2    <21    High    Male        Married   No
2    3  21-35    High    Male         Single  Yes
3    4    >35  Medium    Male         Single  Yes
4    5    >35     Low  Female         Single  Yes
5    6    >35     Low  Female        Married   No
6    7  21-35     Low  Female        Married  Yes
7    8    <21  Medium    Male         Single   No
8    9    <21     Low  Female        Married  Yes
9   10    >35  Medium  Female         Single  Yes
10  11    <21  Medium  Female        Married  Yes
11  12  21-35  Medium    Male        Married  Yes
12  13  21-35    High  Female         Single  Yes
13  14    >35  Medium    Male        Married   No

In [4]:
## Removing ID column because it is on no use
dataset=dataset.drop('D',axis=1)
dataset

Age  Income  Gender Marital Status Buys
0     <21    High    Male         Single   No
1     <21    High    Male        Married   No
2   21-35    High    Male         Single  Yes
3     >35  Medium    Male         Single  Yes
4     >35     Low  Female         Single  Yes
5     >35     Low  Female        Married   No
6   21-35     Low  Female        Married  Yes
7     <21  Medium    Male         Single   No
8     <21     Low  Female        Married  Yes
9     >35  Medium  Female         Single  Yes
10    <21  Medium  Female        Married  Yes
11  21-35  Medium    Male        Married  Yes
12  21-35    High  Female         Single  Yes
13    >35  Medium    Male        Married   No

In [5]:
dataset.dtypes

Age               object
Income            object
Gender            object
Marital Status    object
Buys              object
dtype: object

In [6]:
##Checking null values in dataset

dataset.isnull().sum()


#There are no null values found

Age               0
Income            0
Gender            0
Marital Status    0
Buys              0
dtype: int64

In [7]:
#Sorting out dependant and independant variables
##Dependant and Independant variables

#Independant variables

X=dataset[['Age','Income','Gender','Marital Status']]

#Dependant variables

y=dataset[['Buys']]



In [8]:
X

Age  Income  Gender Marital Status
0     <21    High    Male         Single
1     <21    High    Male        Married
2   21-35    High    Male         Single
3     >35  Medium    Male         Single
4     >35     Low  Female         Single
5     >35     Low  Female        Married
6   21-35     Low  Female        Married
7     <21  Medium    Male         Single
8     <21     Low  Female        Married
9     >35  Medium  Female         Single
10    <21  Medium  Female        Married
11  21-35  Medium    Male        Married
12  21-35    High  Female         Single
13    >35  Medium    Male        Married

In [9]:
y

Buys
0    No
1    No
2   Yes
3   Yes
4   Yes
5    No
6   Yes
7    No
8   Yes
9   Yes
10  Yes
11  Yes
12  Yes
13   No

Here our data in columns Income Gender and Marital Status is in categorical form which needs to be converted into numeric form for that we use label encoder

In [10]:


from sklearn import preprocessing
X=X.apply(preprocessing.LabelEncoder().fit_transform)

print(X)




    Age  Income  Gender  Marital Status
0     1       0       1               1
1     1       0       1               0
2     0       0       1               1
3     2       2       1               1
4     2       1       0               1
5     2       1       0               0
6     0       1       0               0
7     1       2       1               1
8     1       1       0               0
9     2       2       0               1
10    1       2       0               0
11    0       2       1               0
12    0       0       0               1
13    2       2       1               0


Now we have coverted 
age 

<21-1
21-35-0
>35-2

Income
low-1
Medium-2
High-0

gender
Male-1
Female-0

Marital Status

Married-0
Single-1



In [11]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# Train TEst split

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)

In [13]:
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# Prediction 



[Age < 21, Income = Low, Gender = Female, Marital Status = Married]

If above criteria are met to buy the cosmetics?

In [14]:
dataset

Age  Income  Gender Marital Status Buys
0     <21    High    Male         Single   No
1     <21    High    Male        Married   No
2   21-35    High    Male         Single  Yes
3     >35  Medium    Male         Single  Yes
4     >35     Low  Female         Single  Yes
5     >35     Low  Female        Married   No
6   21-35     Low  Female        Married  Yes
7     <21  Medium    Male         Single   No
8     <21     Low  Female        Married  Yes
9     >35  Medium  Female         Single  Yes
10    <21  Medium  Female        Married  Yes
11  21-35  Medium    Male        Married  Yes
12  21-35    High  Female         Single  Yes
13    >35  Medium    Male        Married   No

In [27]:
y_pred=classifier.predict(X_test)
y_pred

array(['No', 'Yes', 'No'], dtype=object)

In [15]:
##Predict
test_x=np.array([1,1,0,0])

In [23]:
pred_y=classifier.predict([test_x])


In [24]:
pred_y

array(['No'], dtype=object)

In [28]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 0],
       [2, 1]], dtype=int64)

In [29]:
accuracy_score(y_test,y_pred)

0.3333333333333333

As the accuracy is low we will use another classifier

In [56]:
from sklearn.neighbors import KNeighborsClassifier
classifier_k=KNeighborsClassifier(n_neighbors=3)
classifier_k.fit(X_train, y_train)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [57]:
y_pred=classifier_k.predict(X_test)
y_pred

array(['No', 'Yes', 'Yes'], dtype=object)

In [58]:
pred_y=classifier_k.predict([test_x])

In [59]:
pred_y

array(['No'], dtype=object)

In [60]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[0, 0],
       [1, 2]], dtype=int64)

In [55]:
accuracy_score(y_test,y_pred)

0.6666666666666666

Using Naive Bayes

In [39]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GaussianNB()

In [41]:
y_pred=classifier.predict(X_test)
y_pred

array(['Yes', 'Yes', 'Yes'], dtype='<U3')

In [ ]:
pred_y=classifier.predict([test_x])

In [42]:
pred_y

array(['No'], dtype=object)

In [ ]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

In [ ]:
accuracy_score(y_test,y_pred)

In [43]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[3]], dtype=int64)

In [45]:
y_pred=classifier.predict(X_test)
y_pred

array(['Yes', 'Yes', 'Yes'], dtype='<U3')

In [46]:
pred_y=classifier.predict([test_x])

In [47]:
pred_y

array(['Yes'], dtype='<U3')

USing Naive bayes we are getting correct observation

In [48]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[3]], dtype=int64)

In [49]:
accuracy_score(y_test,y_pred)

1.0